### ISSUE TITLE
Unify exception handling, less coupling to Invenio

### ISSUE THREAD

**Issue by jalavik** [inspirehep/harvesting-kit#39]
We should unify all the exception handling. Right now much can be handled with `invenio.register_exception`, but in fact it would be good to avoid using Invenio functions in order to keep harvesting-kit a separate package.

In addition the bibtasklets using Invenio should be in overlays instead (like scoap3 or inspire).

See also comments made here: https://github.com/inspirehep/harvesting-kit/pull/37

**Comment by kaplun** [comment]
harvestingkit has been superseeded by inspirehep/hepcrawl
