### ISSUE TITLE
Fix messges for OUP

### ISSUE THREAD

**Issue by Dziolas** [inspirehep/harvesting-kit#54]
Downloading tar package 1 of 4: ptep_iss_2014_7_20140701.pdf.zip
Downloading tar package 2 of 4: ptep_iss_2014_7_20140701.xml.zip
Downloading tar package 4 of 4: ptep_iss_2014_7_20140701_archival_pdf.zip

Number 3 is missing.

**Comment by kaplun** [comment]
harvestingkit has been superseeded by inspirehep/hepcrawl
